server:
  port: 8989           #端口号
  context-path: /w   #项目名
  jsp-servlet:
    init-parameters:
      development: true   #  jsp 的热部署
spring:
  datasource:   #配置数据源
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3309/wsx
    username: root
    password: root
  mvc:        #jsp  视图解析器
    view:
      suffix: .jsp
      prefix: /
mybatis:
  type-aliases-package:  com.baizhi.wsx.entity          #起别名
  mapper-locations: classpath:com/baizhi/dao/*Mapper.xml   #注册Mapper文件